// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_s4-szlidAZZy2hLSKPNe0eYvhiA7LU4',
    appId: '1:737554974480:web:aa24efe19fffba3ab4c795',
    messagingSenderId: '737554974480',
    projectId: 'fir-basics-1049b',
    authDomain: 'fir-basics-1049b.firebaseapp.com',
    storageBucket: 'fir-basics-1049b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClwyUeD-_grIAf7tSWacomxQ3mquVnqzY',
    appId: '1:737554974480:android:531104c131af6f4cb4c795',
    messagingSenderId: '737554974480',
    projectId: 'fir-basics-1049b',
    storageBucket: 'fir-basics-1049b.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_s4-szlidAZZy2hLSKPNe0eYvhiA7LU4',
    appId: '1:737554974480:web:25f01a1b6bc6f754b4c795',
    messagingSenderId: '737554974480',
    projectId: 'fir-basics-1049b',
    authDomain: 'fir-basics-1049b.firebaseapp.com',
    storageBucket: 'fir-basics-1049b.firebasestorage.app',
  );
}
