// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACBtUwewCkIEFEMBGzUIRfffc7HXwLT_U',
    appId: '1:729183180340:web:2e7ad2187b6cb907145c61',
    messagingSenderId: '729183180340',
    projectId: 'agenda-b5abc',
    authDomain: 'agenda-b5abc.firebaseapp.com',
    storageBucket: 'agenda-b5abc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgrbRUTnxMxzaCNpcv-h7ss_bcnjlVO-Y',
    appId: '1:729183180340:android:685da9667cbf07f0145c61',
    messagingSenderId: '729183180340',
    projectId: 'agenda-b5abc',
    storageBucket: 'agenda-b5abc.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACBtUwewCkIEFEMBGzUIRfffc7HXwLT_U',
    appId: '1:729183180340:web:c947d4bdcd921694145c61',
    messagingSenderId: '729183180340',
    projectId: 'agenda-b5abc',
    authDomain: 'agenda-b5abc.firebaseapp.com',
    storageBucket: 'agenda-b5abc.firebasestorage.app',
  );

}